version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/blok
    steps:
      - checkout
      - run: mvn clean package
      - run: ls
      - store_artifacts:
          path: NightShadeUHC/target/UHC.jar
          destination: artifacts
      - store_artifacts:
          path: NightShadeCore/target/Core.jar
          destination: artifacts
      - add_ssh_keys
      - run: ls artifacts
      - deploy:
          name: Deploy to servers
          command: |
            ssh -o BatchMode=yes -o StrictHostKeyChecking=no dhillon@158.69.121.66 "uptime"
            scp ./target/UHC.jar dhillon@158.69.121.66:~/minecraft/template/UHC.jar
            scp ./target/Core.jar dhillon@158.69.121.66:~/minecraft/template/Core.jar
            echo "Finished uploading jars!"