name: NightCheat
version: ${project.version}
main: com.nightshadepvp.nightcheat.NightCheat
authors: [Blok]
depend: [Core, ProtocolLib]
description: Exploit and minimal cheat prevention
website: discord.nightshadepvp.com
commands:
  nightcheatdebug:
    description: Receive debug messages
    aliases: [ncdebug, debugnc]